---
version: "3"
services:
 devopsdb:
   image: naveen3032/repo:db-image
   ports:
     - "3306:3306"
   deploy:
     replicas: 3

 application:
   image: naveen3032/repo:app-image
   ports:
     - "1234:8080"
   deploy:
      replicas: 6

